In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent = ['the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [3]:
sent 

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[5955, 4093, 7194, 7788],
 [5955, 4093, 7194, 649],
 [5955, 4425, 7194, 6992],
 [5746, 9748, 3647, 8852, 951],
 [5746, 9748, 3647, 8852, 8864],
 [4646, 5955, 9609, 7194, 4593],
 [9272, 78, 7047, 8852]]

#### Word Embedding Representation

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8   # Setting max length with help of pad_sequence  if theres only 4 words pad add 3 more zero to make every sent same length
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5955 4093 7194 7788]
 [   0    0    0    0 5955 4093 7194  649]
 [   0    0    0    0 5955 4425 7194 6992]
 [   0    0    0 5746 9748 3647 8852  951]
 [   0    0    0 5746 9748 3647 8852 8864]
 [   0    0    0 4646 5955 9609 7194 4593]
 [   0    0    0    0 9272   78 7047 8852]]


##### feature representation


In [10]:
dim=10  # 10 dimensions

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\Fathi\anaconda3\envs\venv\lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.build(input_shape=(None, sent_length))

In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step


array([[[ 0.03076202,  0.03785268, -0.01094217, -0.02556604,
         -0.0131251 ,  0.03417308,  0.02265748,  0.00290173,
          0.03649205, -0.00833973],
        [ 0.03076202,  0.03785268, -0.01094217, -0.02556604,
         -0.0131251 ,  0.03417308,  0.02265748,  0.00290173,
          0.03649205, -0.00833973],
        [ 0.03076202,  0.03785268, -0.01094217, -0.02556604,
         -0.0131251 ,  0.03417308,  0.02265748,  0.00290173,
          0.03649205, -0.00833973],
        [ 0.03076202,  0.03785268, -0.01094217, -0.02556604,
         -0.0131251 ,  0.03417308,  0.02265748,  0.00290173,
          0.03649205, -0.00833973],
        [ 0.01785454,  0.01638163,  0.04748288, -0.04315161,
         -0.02166638, -0.04104429, -0.02106272, -0.02505541,
         -0.01124251,  0.01782301],
        [-0.03341372,  0.04406771,  0.00535369, -0.03813686,
         -0.04701018, -0.00592718, -0.02270817, -0.02684375,
         -0.04766308,  0.03064616],
        [-0.04656705, -0.00139261,  0.01088382,  0.0

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 5955, 4093, 7194, 7788], dtype=int32)